package dns

import (
	"context"
	"net"
	"strings"
	"sync/atomic"
	"testing"
	"time"
)

// Ground truth for every reverse-name expectation below is Python's
// ipaddress.reverse_pointer, which is an independent implementation of RFC 1035
// section 3.5. Getting the order wrong asks about a different address than the
// user named, and that fails silently as an empty answer.

// ptrServer answers a PTR query for one address and counts what it was asked.
type ptrServer struct {
	addr     string
	hits     atomic.Int64
	askedFor atomic.Value // string: the name the resolver put on the wire
}

func (s *ptrServer) answer(name string) []byte {
	s.askedFor.Store(name)
	msg := make([]byte, 12)
	msg[2], msg[3] = 0x81, 0x80 // QR + RD + RA
	msg[6], msg[7] = 0, 1       // ANCOUNT 1
	msg = append(msg, encodeName(name)...)
	msg = appendUint16(msg, 12) // PTR
	msg = appendUint16(msg, 1)  // class IN
	msg = appendUint32(msg, 900)
	// The rdata length is computed from the encoded name rather than written as
	// a literal. Hardcoding it is how a test ends up asserting that a malformed
	// record decodes cleanly, because the decoder correctly refuses it and the
	// test then fails for the wrong reason.
	target := encodeName("host.example.net")
	msg = appendUint16(msg, uint16(len(target)))
	msg = append(msg, target...)
	return msg
}

// startPTRServer runs a UDP nameserver that answers any PTR query.
func startPTRServer(t *testing.T) *ptrServer {
	t.Helper()
	s := &ptrServer{}
	conn, err := net.ListenPacket("udp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("udp listen: %v", err)
	}
	t.Cleanup(func() { conn.Close() })
	s.addr = conn.LocalAddr().String()

	go func() {
		buf := make([]byte, 512)
		for {
			_, addr, err := conn.ReadFrom(buf)
			if err != nil {
				return
			}
			s.hits.Add(1)
			// The question section starts after the 12-byte header.
			name, _, err := readName(buf, 12)
			if err != nil {
				continue
			}
			_, _ = conn.WriteTo(s.answer(name), addr)
		}
	}()
	return s
}

// --server was silently ignored for every reverse lookup: lookupPTR called
// net.DefaultResolver.LookupAddr unconditionally, so the tool printed the
// requested nameserver in its header and then asked the operating system.
// A user comparing resolvers was comparing nothing, and a reverse lookup could
// not be pointed at a server that does not share the local resolver's view.
func TestPTRUsesTheConfiguredServerNotTheSystemResolver(t *testing.T) {
	srv := startPTRServer(t)
	r := New(Options{Servers: []string{srv.addr}, Timeout: 3 * time.Second})

	result, err := r.Lookup(context.Background(), "192.0.2.10", "PTR")
	if err != nil {
		t.Fatalf("Lookup failed: %v", err)
	}
	if srv.hits.Load() == 0 {
		t.Fatal("the configured server was never queried, so --server is being ignored for PTR")
	}
	if got, _ := srv.askedFor.Load().(string); got != "10.2.0.192.in-addr.arpa" {
		t.Errorf("queried name = %q, want 10.2.0.192.in-addr.arpa", got)
	}
	// The user asked about an address, so the result names the address rather
	// than leaking the internal arpa name into the output.
	if result.Name != "192.0.2.10" {
		t.Errorf("Result.Name = %q, want the address 192.0.2.10", result.Name)
	}
	if len(result.Records) != 1 || result.Records[0].Value != "host.example.net" {
		t.Errorf("records = %+v, want one PTR to host.example.net", result.Records)
	}
}

// Every expectation below was generated by CPython's ipaddress.reverse_pointer,
// not typed by hand: a 32-nibble IPv6 name with one extra "0." looks identical
// to the eye, and a test asserting a hand-typed value fails for a reason that
// has nothing to do with the code under test. Regenerate with the same script
// if a case is added.
func TestReverseNameMatchesPythonIpaddress(t *testing.T) {
	cases := map[string]string{
		"1.1.1.1":              "1.1.1.1.in-addr.arpa",
		"8.8.8.8":              "8.8.8.8.in-addr.arpa",
		"192.0.2.10":           "10.2.0.192.in-addr.arpa",
		"198.51.100.7":         "7.100.51.198.in-addr.arpa",
		"255.255.255.0":        "0.255.255.255.in-addr.arpa",
		"203.0.113.1":          "1.113.0.203.in-addr.arpa",
		"4.4.8.8":              "8.8.4.4.in-addr.arpa",
		"::1":                  "1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa",
		"2001:4860:4860::8888": "8.8.8.8.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.6.8.4.0.6.8.4.1.0.0.2.ip6.arpa",
		"2606:4700:4700::1111": "1.1.1.1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.7.4.0.0.7.4.6.0.6.2.ip6.arpa",
		"2001:db8::1":          "1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.b.d.0.1.0.0.2.ip6.arpa",
	}
	for address, want := range cases {
		ip := net.ParseIP(address)
		if ip == nil {
			t.Fatalf("test data is wrong: %q is not an IP", address)
		}
		if got := reverseName(ip); got != want {
			t.Errorf("reverseName(%s) = %q, want %q", address, got, want)
		}
	}
}

// A zero TTL means "this source has no TTLs", not "expire immediately". The
// system resolver does not expose them, so the renderer needs to be able to
// tell the two apart or it prints a confident "ttl=0".
func TestSystemResolverRecordsReportNoTTL(t *testing.T) {
	r := New(Options{})
	result, err := r.Lookup(context.Background(), "localhost", "A")
	if err != nil {
		t.Skipf("localhost did not resolve through the system resolver: %v", err)
	}
	if len(result.Records) == 0 {
		t.Skip("no A record for localhost")
	}
	for _, record := range result.Records {
		if record.TTLKnown {
			t.Errorf("record %q claims a known TTL of %d, but the system resolver exposes none",
				record.Value, record.TTL)
		}
	}
}

// A TTL that came off the wire is known, and must survive parseAnswer.
func TestParsedRecordsCarryTheirWireTTL(t *testing.T) {
	msg := headerWithAnswers(1)
	msg = appendRecord(msg, "a.example.com", 1, 1, 300, []byte{93, 184, 216, 34})

	records, _, err := parseAnswer(msg, TypeA)
	if err != nil {
		t.Fatalf("parseAnswer failed: %v", err)
	}
	if len(records) != 1 {
		t.Fatalf("got %d records, want 1", len(records))
	}
	if records[0].TTL != 300 {
		t.Errorf("TTL = %d, want 300", records[0].TTL)
	}
	if !records[0].TTLKnown {
		t.Error("a TTL read off the wire must be marked known")
	}
}

// --all walked AllTypes, which includes PTR, so every --all ended with the
// error "google.com is not an IP address". That reads as the server failing
// rather than as a question that cannot apply to a name.
func TestForwardTypesExcludePTR(t *testing.T) {
	for _, t2 := range ForwardTypes {
		if t2 == TypePTR {
			t.Fatal("--all must not ask a PTR question about a name")
		}
	}
	if len(ForwardTypes) != len(AllTypes)-1 {
		t.Errorf("ForwardTypes has %d entries, AllTypes has %d; the only difference should be PTR",
			len(ForwardTypes), len(AllTypes))
	}
	// Everything else must still be covered, or --all silently loses a type.
	for _, want := range AllTypes {
		found := false
		for _, got := range ForwardTypes {
			if got == want {
				found = true
				break
			}
		}
		if !found && want != TypePTR {
			t.Errorf("ForwardTypes is missing %s", want)
		}
	}
}

// The resolver's own error must name the address, or a user who typed a
// hostname instead of an address gets told nothing useful.
func TestPTRRejectsANonAddress(t *testing.T) {
	r := New(Options{Servers: []string{"127.0.0.1:1"}, Timeout: time.Second})
	_, err := r.Lookup(context.Background(), "example.com", "PTR")
	if err == nil {
		t.Fatal("a name must be rejected for a PTR lookup")
	}
	if !strings.Contains(err.Error(), "example.com") {
		t.Errorf("error %q should name the argument the user typed", err)
	}
}
